### ISSUE TITLE
Cannot build the app via import in android studio

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [AllanHasegawa/Tomo#1]

**Comment by AllanHasegawa** [comment]
Hey, do you have more details about the error you're getting?

Can you build de app on the command line? Try: `./gradlew :showcase:assembleDebug`

**Comment by AllanHasegawa** [comment]
The setup should work just fine now :)

Note that you still need to declare your TMDB Api Key in the `local.properties` file, but now this file will be properly created during the first build :)

Feel free to re-open this issue if you still have any problems.
